//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterSbsa {
    
    
    public partial class VivaVozAppGetConfig {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new MasterSbsa.VivaVozAppGet Master {
            get {
                return ((MasterSbsa.VivaVozAppGet)(base.Master));
            }
        }
    }
}
